name: "Terraform Workflow for Lambda"
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      aws-region:
        type: string
        required: true
      aws-statefile-key:
        type: string
        required: true
      aws-lock-dynamodb-table:
        type: string
        required: true
      destroy:
        type: string
        required: false
        default: 'false'
    secrets:
      aws-assume-role-arn:
        required: true
      aws-statefile-s3-bucket:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run packaging script
        run: |
          chmod +x scripts/package.sh
          ./scripts/package.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-assume-role-arn }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws-region }}

      - name: Configure kubectl
        if: ${{ inputs.destroy != 'true' }}
        run: |
          aws eks update-kubeconfig \
            --region ${{ inputs.aws-region }} \
            --name lanchonete-app-dev

      - name: Get LoadBalancer DNS
        if: ${{ inputs.destroy != 'true' }}
        id: get_lb
        run: |
          LB_DNS_PRODUTO=$(kubectl get svc produto-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          LB_DNS_PEDIDO=$(kubectl get svc pedido-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          LB_DNS_PAGAMENTO=$(kubectl get svc pagamento-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          LB_DNS_PRODUCAO=$(kubectl get svc producao-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "LB_DNS_PRODUTO=$LB_DNS_PRODUTO" >> $GITHUB_ENV
          echo "LB_DNS_PEDIDO=$LB_DNS_PEDIDO" >> $GITHUB_ENV
          echo "LB_DNS_PAGAMENTO=$LB_DNS_PAGAMENTO" >> $GITHUB_ENV
          echo "LB_DNS_PRODUCAO=$LB_DNS_PRODUCAO" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ inputs.aws-statefile-s3-bucket }}" \
            -backend-config="key=${{ inputs.aws-statefile-key }}" \
            -backend-config="region=${{ inputs.aws-region }}" \
            -backend-config="dynamodb_table=${{ inputs.aws-lock-dynamodb-table }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Destroy
        if:  ${{ inputs.destroy == 'true' }}
        run: |
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
          terraform destroy -auto-approve

      - name: Terraform Plan
        if: ${{ inputs.destroy != 'true' }}
        run: |
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
          terraform plan \
            -out="${{ inputs.environment }}.plan" \
            -var='services={
              produto_service_dns = "${{ env.LB_DNS_PRODUTO }}"
              pedido_service_dns  = "${{ env.LB_DNS_PEDIDO }}"
              pagamento_service_dns    = "${{ env.LB_DNS_PAGAMENTO }}"
              producao_service_dns    = "${{ env.LB_DNS_PRODUCAO }}"
            }'

      - name: Terraform Apply
        if: ${{ inputs.destroy != 'true' }}
        run: |
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
          terraform apply -auto-approve "${{ inputs.environment }}.plan"